language: python
python:
- 3.5
- 3.8
env:
- TOXENV=django22
- TOXENV=quality
- TOXENV=docs
- TOXENV=pii_check
cache:
- pip
before_install:
- pip install pip==20.0.2
install:
- pip install -r requirements/travis.txt
script:
- tox
after_success:
- codecov
deploy:
  provider: pypi
  user: edx
  distributions: sdist bdist_wheel
  on:
    tags: true
    python: 3.5
    condition: "$TOXENV = quality"
  password:
    secure: XdEbWoQWh9WHvCoKw797L0mBFm2TABRqVLNESGdtIRVQGEMiG/PlhGDMedJEQk+FD036Af2eoAXR7rhE1G8oH2NnnzvnHGTBL9cqJzt1fJtOV7cZRRUi+wLNk5Jr2Q7JnNrc7sULv5iE8TOxQZ3Vc/qoeewWzgppuH2YHqmCR3p8eCPgIjiUaIESk1i126BgfRbk22ody7xDuzWrGAB7BatgSMrt3wMJR8YCCJd6FvpuwIMW08I01x9zeptoIuuMSUNdTu7QVPJqn1XYG0CW04pmyZZenygeIdGVyFrX4ko0pJEZFSthUszcDRfSp+POE77ZIAdazGijOf8VayyFFnAAXPrtYJ12Pj1srau7LTDDYEzYNUzc2vzdJmVKbmkze4nqlQi200PjAdt6F7Jxleqekho20IMGo96+F/CWh/I3Ym+3DqVD9Cl9DY8RZKJXNkV7+/qp9259a5EPftmrIhSEjGdNfy87lkVvP6uSO9GQZsUe/aDzrvPWkNYTuIklmQzBeO6EMuG//P1riKi4NUeqX1uMuqz5Z3IwmY5Dmq+OpqliLbzU5yye4M55xkp2tWUXESB3AUKbP1HDP4FLmcReCrPe+fNNSoss4W6xUYtU1EkEDnL+M1jSABkbC7CWbaxPlXWxxqgvvl40+eodfkq9LCAVfcOyh2PqJSZahmo=
